# Generated by Django 5.1.7 on 2025-05-10 15:42

import django.core.validators
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='technology',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'This field only allows alphabets and spaces.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='applications/resumes/', validators=[jobs.models.validate_file]),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'This field only allows alphabets and spaces.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[jobs.models.validate_file]),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
