# Generated by Django 5.1.7 on 2025-05-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_userprofile_career_goals_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='career_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio_url',
        ),
    ]
