# Generated by Django 5.1.7 on 2025-05-15 18:25

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_userprofile_education_userprofile_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_url',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[jobs.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[jobs.models.validate_file]),
        ),
    ]
