# Generated by Django 5.1.7 on 2025-05-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_userprofile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='technology',
        ),
    ]
