# Generated by Django 5.1.7 on 2025-05-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_job_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_company',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(choices=[('FRESHER', 'Fresher / Entry-Level'), ('MID_LEVEL', 'Mid-Level / Intermediate'), ('EXPERIENCED', 'Experienced / Senior')], default='FRESHER', max_length=20),
        ),
    ]
